"""new fields for zone

Revision ID: 13c36090af06
Revises: 2a04ef5a2aef
Create Date: 2023-07-29 11:25:19.209396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c36090af06'
down_revision = '2a04ef5a2aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registered_at', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zone', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('registered_at')

    # ### end Alembic commands ###
